CXX=g++
CXXFLAGS=-std=c++17 -Wall -Wextra -DWMPINT_DEBUG_MODE
LDFLAGS=-s

CXXFLAGS+=-O2 -march=native
#CXXFLAGS+=-O0

test: test.cc test_initialization.cc test_addition.cc test_multiplication.cc test_fullmultiplication.cc test_misc.cc ../WMPInt.cc
